### PR TITLE
Rewriting all the things

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Still working on this, but it already feels great, so I decided to open this up for revision!

### CODE REVIEW

**Comment by daybugging** [comment]
Looks real great!

**Comment by S1SYPHOS** [comment]
I‘m currently working on Cwebp.php refactoring .. it‘s not much, but it‘s something :dancer:

**Comment by S1SYPHOS** [comment]
With `Ewww.php` being polished, README is next!

**Comment by S1SYPHOS** [comment]
That's it for now - let me know what you think.
I'd be glad to see this merged!

**Comment by rosell-dk** [comment]
Ok, great. I look forward to review and test when I get back. Btw, did you get my email to hello@twobrains.io?

**Comment by S1SYPHOS** [comment]
It should be hello@twobrain.io, let me check ..

**Comment by S1SYPHOS** [comment]
Alright, back from my easter holidays, let me know where we stand! I‘ll add more tests eventually and Travis too, but the merge doesn‘t depend on this! :sunny:

**Comment by S1SYPHOS** [comment]
There's some more, and I guess testing will be finished tomorrow. Looking forward to your review of all changes, until then, have a good time!

**Comment by rosell-dk** [comment]
I have an open time slot. I'll do it

**Comment by S1SYPHOS** [comment]
Well, I thought the command pattern rewrite would come first, but alright :)

**Pull request merged**
